---
azs:
- name: z1
  cloud_properties: {availability_zone: us-east-1a}

networks:
- name: default
  type: manual
  subnets:
  - range: 10.10.0.0/24
    gateway: 10.10.0.1
    dns: [10.0.0.2]
    reserved: ["10.10.0.2 - 10.10.0.20", "10.10.0.119"]
    static: ["10.10.0.100 - 10.10.0.105"]
    cloud_properties:
      {"subnet":"subnet-63196648"}

- name: vip_network
  type: vip
  cloud_properties: {}

vm_types:
- name: default
  cloud_properties: {"instance_type":"m3.medium","availability_zone":"us-east-1a","ephemeral_disk":{"size":20000,"type":"gp2"}}

compilation:
  workers: 6
  network: default
  reuse_compilation_vms: true
  cloud_properties: {"instance_type":"m3.medium","availability_zone":"us-east-1a","ephemeral_disk":{"size":20000,"type":"gp2"}}

# above is iaas.yml ("cloud config") ^^^
