name: fallback

director_uuid: 879402dd-f9f8-4463-9f05-xxxxxxxxxx

releases:
- name: dummy
  version: latest
- name: syslog
  version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 10
  max_in_flight: 10
  canary_watch_time: 30000-600000
  update_watch_time: 5000-600000
  serial: false

instance_groups:
- name: dummy_with_package
  jobs:
  - name: dummy_with_package
    release: dummy
  - name: syslog_forwarder
    release: syslog
    consumes:
      syslog_storer: {from: primary_syslog_storer}
  instances: 1
  vm_type: default
  stemcell: default
  networks:
  - name: default
  properties:
    syslog:
      address: 10.10.0.102
      port: 514
      transport: tcp
      fallback_servers:
      - address: 10.10.0.103
        port: 514
        transport: tcp

- name: syslog_storer_primary
  jobs:
  - name: syslog_storer
    release: syslog
    provides:
      syslog_storer: {as: primary_syslog_storer}
  instances: 1
  vm_type: default
  stemcell: default
  networks:
  - name: default
    static_ips: [10.10.0.102]
  properties:
    syslog:
      transport: tcp

- name: syslog_storer_fallback
  jobs:
  - name: syslog_storer
    release: syslog
  instances: 1
  vm_type: default
  stemcell: default
  networks:
  - name: default
    static_ips: [10.10.0.103]
  properties:
    syslog:
      transport: tcp
